global:
  resolve_timeout: 5m

route:
  receiver: 'telegram-notifications'
  group_by: ['alertname', 'job']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h

receivers:
- name: 'telegram-notifications'
  telegram_configs:
  - bot_token_file: '/etc/alertmanager/secrets/telegram_bot_token'
    # ИСПРАВЛЕНИЕ: Указываем ID чата как число, напрямую.
    # Это единственный способ, который поймет Alertmanager.
    chat_id: -1002743466882
    parse_mode: 'HTML'
    message: |
      {{ range .Alerts }}
      <b>{{ if eq .Status "firing" }}🔥 FIRING 🔥{{ else }}✅ RESOLVED ✅{{ end }}</b>
      <b>Alert:</b> {{ .Labels.alertname }}
      <b>Severity:</b> {{ .Labels.severity | toUpper }}
      <b>Description:</b> {{ .Annotations.description }}
      <a href="{{ .GeneratorURL }}">Prometheus Graph</a>
      {{ end }}
    send_resolved: true
