# --- Зависимости для работы приложения ---
requires 'Mojolicious';
requires 'Digest::SHA';
requires 'Time::HiRes';
# УДАЛЯЕМ старую зависимость 'DB_File'
# ДОБАВЛЯЕМ новый, удобный клиент для CouchDB
requires 'Mojo::CouchDB';

# --- Зависимость для метрик ---
requires 'Mojolicious::Plugin::Prometheus';
