# --- Зависимости для работы приложения ---
requires 'Mojolicious';
requires 'DB_File';
requires 'Digest::SHA';
requires 'Storable';
requires 'Time::HiRes';
# --- Новая зависимость для метрик ---
requires 'Mojolicious::Plugin::Prometheus';