version: '3.8'

services:
  # Сервис 1: Наше приложение Pastebin
  pastebin:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data

  # Сервис 2: Prometheus (сборщик метрик)
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  # Сервис 3: Grafana (визуализатор графиков)
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3100:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  # НОВЫЙ СЕРВИС 4: Locust (нагрузочный тестер)
  locust:
    image: locustio/locust
    ports:
      # Веб-интерфейс Locust будет доступен на порту 8089
      - "8089:8089"
    volumes:
      # Подключаем папку с нашим скриптом
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py

volumes:
  prometheus_data: {}
  grafana_data: {}
