version: '3.8'

services:
  pastebin:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./hypnotoad.conf:/app/hypnotoad.conf

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3100:3000"
    environment:
      GF_SECURE_SETTINGS_TELEGRAM_BOT_TOKEN: "${BOT_TOKEN}"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  # --- ИЗМЕНЕННАЯ СЕКЦИЯ LOCUST ---
  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    # ИЗМЕНЕНИЕ 1: Мы монтируем наш скрипт прямо в рабочую директорию контейнера
    volumes:
      - ./locust/locustfile.py:/home/locust/locustfile.py
    # ИЗМЕНЕНИЕ 2: Мы полностью УБИРАЕМ command.
    # Теперь Docker запустит команду по умолчанию из образа Locust,
    # которая автоматически найдет locustfile.py в своей домашней директории.

volumes:
  prometheus_data: {}
  grafana_data: {}
