version: '3.8'

services:
  pastebin:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
      - ./hypnotoad.conf:/app/hypnotoad.conf

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3100:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  locust:
    image: locustio/locust
    ports:
      - "8089:8089"
    volumes:
      - ./locust:/mnt/locust
    command: -f /mnt/locust/locustfile.py

  alertmanager:
    image: prom/alertmanager:latest
    ports:
      - "9093:9093"
    volumes:
      # Монтируем всю папку с конфигурацией
      - ./alertmanager/:/config/
      # ИСПРАВЛЕНИЕ: Отдельно монтируем файл с секретом в нужную директорию
      # :ro делает файл доступным только для чтения внутри контейнера - это лучшая практика
      - ./secrets/telegram_bot_token:/etc/alertmanager/secrets/telegram_bot_token:ro
    command: '--config.file=/config/config.yml'

volumes:
  prometheus_data: {}
  grafana_data: {}
